version: '2'

services:
  nginx:
    build:
      context: ./service/nginx
      args:
        CONTAINER_TIME_ZONE: ${CONTAINER_TIME_ZONE}
        CONTAINER_CHANGE_SOURCE: ${CONTAINER_CHANGE_SOURCE}
    privileged: true
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${NGINX_DIR}nginx.conf:/etc/nginx/nginx.conf
      - ${APPLICATION_DIR}:/etc/nginx/html/
      - ${NGINX_DIR}conf.d/:/etc/nginx/conf.d/
      - ${NGINX_DIR}log/:/var/log/nginx/

  mysql57:
    build:
      context: ./service/mysql/57
      args:
        CONTAINER_TIME_ZONE: ${CONTAINER_TIME_ZONE}
        CONTAINER_CHANGE_SOURCE: ${CONTAINER_CHANGE_SOURCE}
    privileged: true
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_DATA_DIR}57/:/var/lib/mysql
      - ${MYSQL_DIR}57/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  redis:
    build:
      context: ./service/redis
      args:
        CONTAINER_TIME_ZONE: ${CONTAINER_TIME_ZONE}
        CONTAINER_CHANGE_SOURCE: ${CONTAINER_CHANGE_SOURCE}
    privileged: true
    ports:
      - "6379:6379"
    volumes:
      - ${REDIS_DIR}redis.conf:/usr/local/etc/redis/redis.conf
      - ${REDIS_DATA_DIR}:/data

  anyproxy:
    build:
      context: ./service/anyproxy
      args:
        CONTAINER_TIME_ZONE: ${CONTAINER_TIME_ZONE}
        CONTAINER_CHANGE_SOURCE: ${CONTAINER_CHANGE_SOURCE}
    privileged: true
    ports:
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ${ANYPROXY_RULE_DIR}:/anyproxy/

  grafana:
    build:
      context: ./service/grafana
      args:
        CONTAINER_TIME_ZONE: ${CONTAINER_TIME_ZONE}
        CONTAINER_CHANGE_SOURCE: ${CONTAINER_CHANGE_SOURCE}
    privileged: true
    ports:
      - "3000:3000"
    volumes:
      - ${GRAFANA_DATA_DIR}:/var/lib/grafana
      - ${GRAFANA_DIR}custom.ini:/etc/grafana/grafana.ini