version: '2'

services:
  nginx:
    build:
      context: ./service/nginx
      args:
        CONTAINER_TIME_ZONE: ${CONTAINER_TIME_ZONE}
        CONTAINER_CHANGE_SOURCE: ${CONTAINER_CHANGE_SOURCE}
    privileged: true
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    links:
     - "php72"
     - "php56"
    volumes:
      - ${NGINX_DIR}nginx.conf:/etc/nginx/nginx.conf
      - ${APPLICATION_DIR}:/etc/nginx/html/
      - ${NGINX_DIR}conf.d/:/etc/nginx/conf.d/
      - ${NGINX_DIR}php/:/etc/nginx/php/
      - ${NGINX_DIR}log/:/var/log/nginx/

  php72:
    build:
      context: ./service/php/72
      args:
        CONTAINER_TIME_ZONE: ${CONTAINER_TIME_ZONE}
        CONTAINER_CHANGE_SOURCE: ${CONTAINER_CHANGE_SOURCE}
    privileged: true
    ports:
      - "9072:9000"
    volumes:
      - ${APPLICATION_DIR}:/etc/nginx/html/
      - ${PHP_DIR}72/php.ini:/usr/local/etc/php/php.ini
      - ${PHP_DIR}72/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ${PHP_DIR}72/log/:/var/log/

  php56:
    build:
      context: ./service/php/56
      args:
        CONTAINER_TIME_ZONE: ${CONTAINER_TIME_ZONE}
        CONTAINER_CHANGE_SOURCE: ${CONTAINER_CHANGE_SOURCE}
    privileged: true
    ports:
      - "9056:9000"
    volumes:
      - ${APPLICATION_DIR}:/etc/nginx/html/
      - ${PHP_DIR}56/php.ini:/usr/local/etc/php/php.ini
      - ${PHP_DIR}56/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ${PHP_DIR}56/log/:/var/log/

  mysql57:
    build:
      context: ./service/mysql/57
      args:
        CONTAINER_TIME_ZONE: ${CONTAINER_TIME_ZONE}
        CONTAINER_CHANGE_SOURCE: ${CONTAINER_CHANGE_SOURCE}
    privileged: true
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_DATA_DIR}57/:/var/lib/mysql
      - ${MYSQL_DIR}57/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  redis:
    build:
      context: ./service/redis
      args:
        CONTAINER_TIME_ZONE: ${CONTAINER_TIME_ZONE}
        CONTAINER_CHANGE_SOURCE: ${CONTAINER_CHANGE_SOURCE}
    privileged: true
    ports:
      - "6379:6379"
    volumes:
      - ${REDIS_DIR}/redis.conf:/usr/local/etc/redis/redis.conf
      - ${REDIS_DATA_DIR}:/data

  anyproxy:
      build:
        context: ./service/anyproxy
        args:
          CONTAINER_TIME_ZONE: ${CONTAINER_TIME_ZONE}
          CONTAINER_CHANGE_SOURCE: ${CONTAINER_CHANGE_SOURCE}
      privileged: true
      ports:
        - "8001:8001"
        - "8002:8002"
      volumes:
        - ${ANYPROXY_RULE_DIR}/:/anyproxy/
